config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  resources :alunos, only: [:new, :show, :create]
  get 'alunos/show'
  post 'alunos/new'
  get 'homes/index'
  resources :matriculas, only: [:new, :show, :index, :create]
  get 'matriculas/show'
  post 'matriculas/show'
  get 'matricula/new'
  post 'matriculas/new'
  get 'matriculas/index'
  post 'matriculas/index'
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/aluno.rb
class Aluno < ApplicationRecord
  validates :nome, presence: true
  validates :sobrenome, presence: true
  validates :cpf, presence: true, uniqueness: true, length: {maximum: 13}
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }
  validates :telefone, presence: true, format: { with: /\A\(\d{2}\)\s*\d{4,5}\-\d{4}\z/, message: "deve estar no formato (99) 99999-9999" }
  validates :cep, presence: true, format: { with: /\A\d{5}\-\d{3}\z/, message: "deve estar no formato 99999-999"}
  validates :endereco, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/matricula.rb
class Matricula < ApplicationRecord
    validates :matricula, presence: true
    validates :curso, presence: true
    validates :tipo_curso, presence: true
    validates :modalidade, presence: true
    validates :periodo, presence: true
    validates :data_matricula, presence: true
    validates :turno, presence: true
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  def new
    @aluno = Aluno.new
  end

  def show
    @aluno = Aluno.all
  end

  def create
    @aluno = Aluno.new(aluno_params)
    if @aluno.save
      render 'show', notice: 'Cadastro realizado'
    else
      render 'new', notice: 'Erro no cadastro. Tente de novo.'
    end
  end

  private
  def aluno_params
    aluno_params = params.require(:aluno).permit(:nome, :sobrenome, :cpf, :email, :telefone, :cep, :endereco)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/matricula_controller.rb
class MatriculaController < ApplicationController
  def new
  end
end

app/controllers/matriculas_controller.rb
class MatriculasController < ApplicationController
  def index
    @matricula = Matricula.all
  end
  def show
    @matricula = Matricula.find(params[:id])
  end
  def new
    @matricula = Matricula.new
  end
  def create
    @matricula = Matricula.new(matricula_params)
    if @matricula.save
      render matriculas_show_path[:id], notice: 'Matrícula realizada com sucesso'
    else
      render 'new', notice: 'Erro ao matricular. Tente de novo!'
    end
  end

  private
  def matricula_params
    matricula_params = params.require(:matricula).permit(:matricula, :curso, :tipo_curso, :modalidade, :turno, :periodo, :data_matricula)
  end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/matricula_helper.rb
module MatriculaHelper
end

app/helpers/matriculas_helper.rb
module MatriculasHelper
end

app/views/alunos/new.html.erb
<center>
  <h1>Cadastro de Aluno</h1>
  <%= form_with(model: @alunos) do |a| %>
    <div>
      <%= a.label :nome, style: "display: block" %>
      <%= a.text_field :nome %>
    </div>
    <div>
      <%= a.label :sobrenome, style: "display: block" %>
      <%= a.text_field :sobrenome %>
    </div>

    <div>
      <%= a.label :cpf, style: "display: block" %>
      <%= a.text_field :cpf %>
    </div>
    <div>
      <%= a.label :email, style: "display: block" %>
      <%= a.text_field :email %>
    </div>

    <div>
      <%= a.label :telefone, style: "display: block" %>
      <%= a.text_field :telefone %>
    </div>
    <div>
      <%= a.label :cep, style: "display: block" %>
      <%= a.text_field :cep %>
    </div>

    <div>
      <%= a.label :endereco, style: "display: block" %>
      <%= a.text_field :endereco %>
    </div>

    <div>
      <%= a.submit  "Salvar" %>
    </div>
    <div class="botão">
    <%= link_to 'Voltar', root_path %>
    </div>
  <% end %>
<center>

app/views/alunos/show.html.erb
<h1>Alunos cadastrados</h1>
<div class="lista">
  <%= @aluno.each do |a|  %>
      <h2>Nome: </h2>
      <%= a.nome %>
      <h2>Sobrenome: </h2>
      <%= a.sobrenome  %>
      <h2>CPF: </h2>
      <%= a.cpf %>
      <h2>Email: </h2>
      <%= a.email %>
      <h2>Telefone: </h2>
      <%= a.telefone %>
      <h2>CEP: </h2>
      <%= a.cep %>
      <h2>Endereço: </h2>
      <%= a.endereco %>
  <% end %>

  <div>
    <%= link_to 'Voltar', root_path %>
  </div>
</div>

app/views/homes/index.html.erb
<center>
  <h1>Espaço do Administrador</h1>

  <div class="botão">
    <%= link_to 'Cadastrar Aluno', new_aluno_path %>
  </div>

  <div class="botão">
    <%= link_to 'Ver alunos', alunos_show_path %>
  </div>
  <div class="botão">
    <%= link_to 'Alunos matriculados', matriculas_path %>
  </div>
  <div class="botão">
    <%= link_to 'Fazer matricula', new_matricula_path %>
  </div>
  
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortalAdmin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/matriculas/index.html.erb
<h1>Alunos Matriculados</h1>
<div class="lista">
    <%= link_to 'Voltar', root_path %>
</div>

app/views/matriculas/new.html.erb
<h1>Nova Matrícula</h1>
<%= form_with(model: @matriculas) do |m| %>
  <div class="lista">
    <%= m.label 'Matrícula' %>
    <%= m.number_field :matricula %>
  </div>
  <div class="lista">
    <%= m.label 'Curso:' %>
    <%= m.text_field :curso %>
  </div>
  <div class="lista">
    <%= m.label 'Tipo de Curso:' %>
    <%= m.text_field :tipo_curso %>
  </div>
  <div class="lista">
    <%= m.label 'Modalidade:' %>
    <%= m.text_field :modalidade %>
  </div>
    <div class="lista">
    <%= m.label 'Turno:' %>
    <%= m.text_field :turno %>
  </div>
    <div class="lista">
    <%= m.label 'Período:' %>
    <%= m.text_field :periodo %>
  </div>
    <div class="lista">
    <%= m.label 'Data da matrícula' %>
    <%= m.text_field :matricula %>
  </div>
  <div class="botão">
    <%= m.submit %>
  </div>
  <div class="lista">
    <%= link_to 'Voltar', root_path %>
  </div>
<% end %>

app/views/matriculas/show.html.erb
<h1>Alunos Matriculados</h1>
<div class="lista">
    <%= link_to 'Voltar', root_path %>
</div>

<p>Nome: <%= @matricula.matricula %></p>
<p>E-mail: <%= @matricula.email %></p>